from enum import Enum


class EventType(str, Enum):
    """이벤트 타입 정의"""
    SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE"
    RECEIVE_CHAT_MESSAGE = "RECEIVE_CHAT_MESSAGE"
    DISCONNECT = "DISCONNECT"
    CONNECT = "CONNECT"
    ERROR = "ERROR"
    ACCEPT_QUOTATION = "ACCEPT_QUOTATION"
    RECEIVE_QUOTATION_ACCEPTED = "RECEIVE_QUOTATION_ACCEPTED"